### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by 13699531464** [wzy6642/K-Prototypes#1]
总是显示：IndexError: list index out of range 错误

**Comment by wzy6642** [comment]
方便发一下数据吗？

**Comment by 13699531464** [comment]
用的是GTD数据集
[clean_data.zip](https://github.com/wzy6642/K-Prototypes/files/4681562/clean_data.zip)

**Comment by wzy6642** [comment]
你的数据还没有做预处理啊，需要先把缺失值什么的处理一下

**Comment by 13699531464** [comment]
可以发一份当时您做实验的数据集吗，谢谢

**Comment by wzy6642** [comment]
已更新到readme

**Comment by 13699531464** [comment]
非常感谢！
